server:
  port: 80

spring:
  profiles:
    active: testdocker
---
spring:
  profiles: testdocker
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      uri: mongodb://mongoadmin:1111@localhost:27039
      authentication-database: admin
      database: market_index
#      username: mongoadmin
#      password: 1111
#      host: localhost
#      port: 27039